# Uncomment the next line to define a global platform for your project
 platform :ios, ’9.0’

target 'AdminMoney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdminMoney

  target 'AdminMoneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdminMoneyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
